services:
  postgres:
    image: postgres:17-alpine
    container_name: payments-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5434:5432"

    volumes:
      - payments_postgres_data:/var/lib/postgresql/data

volumes:
  payments_postgres_data: