CREATE SCHEMA IF NOT EXISTS auth;

CREATE SCHEMA IF NOT EXISTS users;

CREATE SCHEMA IF NOT EXISTS accounts;

CREATE SCHEMA IF NOT EXISTS transactions;

CREATE SCHEMA IF NOT EXISTS notifications;

CREATE SCHEMA IF NOT EXISTS audit;